### ISSUE TITLE
GitLocalize "Conflict" status

### ISSUE THREAD

**Issue by eugenioamn** [dwmkerr/hacker-laws#269]
I can't edit the pt-BR translation because I'm getting an error while trying to access the respective file on GitLocalize: [error image](https://imgur.com/a/jdSQf2Y). How to solve this?

**Comment by dwmkerr** [comment]
I'm checking with the GitLocalise team now and will let you know when solved, looks like it is broken for me at the moment too, cannot add another language

**Comment by dwmkerr** [comment]
Can you try again now? There was an issue with the project which I think they've fixed now

**Comment by eugenioamn** [comment]
The problem was not solved for me. It says "The resource is now syncing. Please refresh the page in a minute.", but when I refresh the page, nothing changes, that message is still there. Also, the status is still "Conflict". What if you remove me from there and add me again?

**Comment by eugenioamn** [comment]
I don't know what happened, but the problem is solved now.
